-- ShineGo reviews: eenmalig uitvoeren in Supabase SQL Editor

create extension if not exists pgcrypto;

alter table public.boekingen
  add column if not exists review_token uuid not null default gen_random_uuid();

create unique index if not exists boekingen_review_token_key
  on public.boekingen (review_token);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  booking_id bigint not null unique references public.boekingen(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  opmerking text,
  zichtbaar boolean not null default true,
  constraint reviews_opmerking_lengte check (opmerking is null or char_length(opmerking) <= 1000)
);

alter table public.reviews enable row level security;

-- Professionals mogen alleen zichtbare reviews van hun eigen opdrachten lezen.
drop policy if exists "professionals lezen eigen reviews" on public.reviews;
create policy "professionals lezen eigen reviews"
on public.reviews
for select
to authenticated
using (
  zichtbaar = true
  and exists (
    select 1
    from public.boekingen b
    join public.professionals p on p.id = b.professional_id
    where b.id = reviews.booking_id
      and p.user_id = auth.uid()
  )
);

-- Geen publieke INSERT-policy: reviews worden via de server-API opgeslagen.
