export default function ProfessionalVoorwaardenPage() {
  return (
    <main className="min-h-screen bg-slate-50 text-slate-900">
      <div className="mx-auto max-w-4xl px-6 py-12 sm:py-16">
        <a href="/professional" className="mb-8 inline-block font-semibold text-blue-600 hover:text-blue-700">← Terug naar aanmelden</a>

        <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:p-10">
          <p className="text-sm font-bold uppercase tracking-wider text-blue-600">ShineGo</p>
          <h1 className="mt-2 text-3xl font-extrabold tracking-tight sm:text-4xl">Voorwaarden voor professionals</h1>
          <p className="mt-3 text-sm text-slate-500">Laatst bijgewerkt: 25 september 2026</p>

          <div className="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-5 text-sm leading-6 text-slate-700">
            <strong className="text-slate-900">ShineGo</strong><br />
            KvK: 57712913<br />
            Btw-id: NL001205368B47<br />
            E-mail: <a href="mailto:info@shinego.nl" className="font-semibold text-blue-600 underline hover:text-blue-700">info@shinego.nl</a>
          </div>

          <div className="mt-10 space-y-9 leading-7 text-slate-600">
            <section><h2 className="text-xl font-bold text-slate-900">1. Rol van ShineGo</h2><p className="mt-2">ShineGo exploiteert een online bemiddelingsplatform waarop zelfstandige professionals opdrachten van klanten kunnen ontvangen en aannemen. ShineGo faciliteert onder andere de boeking, betaling, communicatie en administratieve afhandeling.</p><p className="mt-2">ShineGo is geen werkgever van de professional en geeft geen dagelijkse leiding aan de uitvoering van de werkzaamheden.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">2. Zelfstandig ondernemerschap en eigen verantwoordelijkheid</h2><p className="mt-2">De professional werkt als zelfstandig ondernemer, handelt voor eigen rekening en risico en is zelf verantwoordelijk voor inschrijving, belastingen, vergunningen, verzekeringen en overige verplichtingen die bij de eigen onderneming horen.</p><p className="mt-2">De professional bepaalt zelf of hij een beschikbare opdracht aanneemt en blijft zelf verantwoordelijk voor planning, vervoer, materiaal, hulpmiddelen, werkmethode, veiligheid en de concrete uitvoering van de aangenomen opdracht.</p><p className="mt-2">De professional is zelf verantwoordelijk voor de keuze om wel of geen bedrijfsaansprakelijkheidsverzekering of andere passende verzekering af te sluiten en voor de omvang van de dekking. Het ontbreken van een verzekering, onvoldoende dekking of een afwijzing door een verzekeraar verschuift de wettelijke verantwoordelijkheid van de professional niet naar ShineGo.</p><p className="mt-2">De professional blijft verantwoordelijk voor schade die volgens de wet aan zijn handelen of nalaten kan worden toegerekend. Dit laat eventuele eigen wettelijke verplichtingen of aansprakelijkheid van ShineGo als platform onverlet.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">3. Registratie en controle</h2><p className="mt-2">De professional verstrekt juiste en actuele bedrijfs- en contactgegevens, waaronder bedrijfsnaam, KvK-nummer en btw-nummer. ShineGo kan deze registratiegegevens handmatig controleren en mag aanvullende informatie of bewijs opvragen wanneer een controle daartoe aanleiding geeft.</p><p className="mt-2">Een bedrijfsaansprakelijkheidsverzekering en het invullen van verzekeraar of polisnummer zijn geen algemene voorwaarde voor activering van een ShineGo-profiel. Als de professional vrijwillig verzekeringsgegevens opgeeft, blijft hij zelf verantwoordelijk voor de juistheid, geldigheid en toereikendheid daarvan. ShineGo geeft door het opslaan of tonen van deze gegevens geen garantie over verzekeringsdekking.</p><p className="mt-2">Een profiel wordt pas geactiveerd nadat ShineGo de vereiste registratiegegevens voldoende heeft kunnen controleren. ShineGo kan een registratie weigeren, tijdelijk beperken of beëindigen wanneer verplichte gegevens onjuist, onvolledig of niet verifieerbaar zijn, of wanneer daar een andere gerechtvaardigde reden voor bestaat.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">4. Beschikbare opdrachten en acceptatie</h2><p className="mt-2">Beschikbare opdrachten kunnen onder meer informatie bevatten over regio, datum, tijd, type pand, bereikbaarheid, verdiepingen, aantal ramen en vergoeding. Persoons- en exacte adresgegevens van de klant worden pas beschikbaar voor zover dat nodig is voor een aangenomen opdracht.</p><p className="mt-2">Door een opdracht te accepteren bevestigt de professional dat hij de beschikbare opdrachtinformatie heeft bekeken en de opdracht in beginsel kan uitvoeren. Bij een wezenlijke afwijking op locatie meldt de professional dit via ShineGo voordat aanvullende werkzaamheden worden uitgevoerd.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">4A. Volgorde en weergave van opdrachten</h2><p className="mt-2">Alleen professionals met een actief en geverifieerd profiel kunnen opdrachten aannemen. De compatibiliteit tussen de diensten en het materiaal in het professionalprofiel en de vereisten van de opdracht bepaalt of een opdracht kan worden aangenomen.</p><p className="mt-2">Beschikbare opdrachten worden in beginsel op gewenste uitvoerdatum en vervolgens op gewenst tijdstip weergegeven. De afstand tot de opdracht wordt berekend op basis van locatiegegevens en kan door de professional als filter worden gebruikt. De ingestelde werkgebiedafstand bepaalt de standaardvoorkeur voor afstand, maar de professional kan de zoekafstand in het dashboard vergroten wanneer die mogelijkheid beschikbaar is.</p><p className="mt-2">ShineGo biedt op dit moment geen mogelijkheid om tegen betaling hoger in de volgorde van beschikbare opdrachten te komen en geeft geen eigen uitvoeringsdienst voorrang boven aanbod van professionals. Als de belangrijkste parameters voor de volgorde wezenlijk veranderen, worden deze voorwaarden overeenkomstig aangepast.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">4B. Toegang tot gegevens</h2><p className="mt-2">ShineGo heeft voor de werking van het platform toegang tot gegevens die de professional zelf verstrekt en tot gegevens die bij het gebruik van het platform ontstaan, zoals bedrijfs- en contactgegevens, werkgebied, diensten, accountstatus, opdrachtstatussen, betalingen, uitbetalingen, beoordelingen en relevante technische of administratieve gegevens.</p><p className="mt-2">De professional kan via zijn account onder meer het eigen profiel, eigen opdrachten, beschikbare opdrachtinformatie, vergoedingen, uitbetalingsstatus en ontvangen beoordelingen inzien voor zover deze functies beschikbaar zijn. Klantgegevens worden alleen beschikbaar gesteld voor zover dit nodig is voor de uitvoering en afhandeling van een opdracht.</p><p className="mt-2">Gegevens kunnen worden gedeeld met klanten, betaaldienstverleners en andere dienstverleners voor zover dit nodig is voor boeking, uitvoering, betaling, uitbetaling, fraudepreventie, ondersteuning of naleving van wettelijke verplichtingen. Na beëindiging van het account kan de directe toegang van de professional eindigen, terwijl ShineGo gegevens kan bewaren voor zover dit nodig is voor administratie, openstaande opdrachten, geschillen, fiscale bewaarplichten of andere wettelijke verplichtingen. Meer informatie staat in de privacyverklaring.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">5. Uitvoering, materiaal en veiligheid</h2><p className="mt-2">De professional bepaalt zelfstandig welke werkmethode, materialen en hulpmiddelen geschikt zijn. Dit geldt onder andere voor traditioneel materiaal, telescoopsteel, water-fed pole en het gebruik van osmose- of ander geschikt reinigingswater.</p><p className="mt-2">De professional beoordeelt de situatie ter plaatse en is zelf verantwoordelijk voor een veilige en deugdelijke uitvoering en voor naleving van toepasselijke wet- en regelgeving. ShineGo schrijft geen concrete werkmethode voor.</p><p className="mt-2">Wanneer de professional van oordeel is dat een situatie niet verantwoord kan worden uitgevoerd, voert hij de opdracht niet uit op een onveilige wijze en meldt hij dit zo snel mogelijk via ShineGo.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">6. Omgang met klanten</h2><p className="mt-2">De professional gedraagt zich professioneel en zorgvuldig tegenover klanten en behandelt klantgegevens uitsluitend voor zover nodig voor de uitvoering van de opdracht.</p><p className="mt-2">Extra werkzaamheden die niet onder de oorspronkelijke boeking vallen worden niet zonder duidelijke afstemming uitgevoerd.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">7. Vergoeding en platformcommissie</h2><p className="mt-2">Voor via ShineGo uitgevoerde opdrachten bedraagt de platformcommissie bij de huidige standaardopzet 15% van het relevante opdrachtbedrag en komt 85% toe aan de professional, tenzij voor een specifieke opdracht vooraf uitdrukkelijk anders is vermeld.</p><p className="mt-2">De vergoeding die voor acceptatie van een opdracht wordt getoond, is leidend voor die opdracht, behoudens correcties bij fouten, terugbetalingen, annuleringen, geschillen of andere situaties die volgens deze voorwaarden tot aanpassing mogen leiden.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">8. Betalingen en betaaldienstverlener</h2><p className="mt-2">Klantbetalingen en uitbetalingen aan professionals kunnen via Stripe of een andere betaaldienstverlener worden verwerkt. De professional moet voldoen aan de verificatie- en uitbetalingsvereisten van de betreffende betaaldienstverlener.</p><p className="mt-2">Betaalverificatie en het koppelen van een uitbetalingsrekening kunnen als aparte stap vanuit het professional-dashboard plaatsvinden.</p><p className="mt-2">Een uitbetaling kan worden uitgesteld zolang noodzakelijke verificatie ontbreekt, een betaling niet definitief is, een geschil loopt, fraude of misbruik wordt onderzocht of een wettelijke verplichting uitbetaling verhindert.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">9. Uitbetalingsschema en afrekening</h2><p className="mt-2">Uitbetalingen worden verwerkt volgens het op dat moment geldende uitbetalingsschema van ShineGo nadat een opdracht volgens de platformprocedure als afgerond en uitbetaalbaar is aangemerkt.</p><p className="mt-2">De professional ontvangt bij of na uitbetaling een afrekening of administratief overzicht met de relevante bedragen en platformcommissie.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">10. Annulering door de professional</h2><p className="mt-2">Wanneer de professional een aangenomen opdracht niet kan uitvoeren, meldt hij dit zo snel mogelijk via ShineGo. ShineGo kan de opdracht opnieuw beschikbaar stellen aan een andere professional.</p><p className="mt-2">Herhaalde, zeer late of ongegronde annuleringen kunnen aanleiding zijn om het account of de toegang tot nieuwe opdrachten tijdelijk te beperken of te beëindigen.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">11. Klant niet thuis of geen toegang</h2><p className="mt-2">Wanneer aanwezigheid of toegang noodzakelijk is en de klant niet aanwezig is of geen toegang verschaft, volgt de professional de geldende no-showprocedure. ShineGo kan vragen om passende informatie of bewijs van aanwezigheid voordat een vergoeding of kosten worden vastgesteld.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">12. Aansprakelijkheid en verzekering</h2><p className="mt-2">De professional blijft verantwoordelijk voor schade die volgens de wet aan zijn handelen of nalaten kan worden toegerekend.</p><p className="mt-2">Een bedrijfsaansprakelijkheidsverzekering (AVB) is op dit moment geen algemene voorwaarde om een ShineGo-profiel te activeren of opdrachten via het platform aan te nemen. De professional blijft als zelfstandig ondernemer zelf verantwoordelijk voor de afweging welke verzekeringen voor de eigen onderneming en werkzaamheden passend of noodzakelijk zijn.</p><p className="mt-2">Wanneer de professional vrijwillig verzekeringsgegevens aan ShineGo verstrekt, moeten deze gegevens juist en actueel zijn. ShineGo kan bij een schadegeval of wanneer daar een gerechtvaardigde aanleiding voor bestaat om aanvullende informatie vragen, maar geeft door het opslaan of controleren van verzekeringsgegevens geen garantie over de dekking.</p><p className="mt-2">Het ontbreken van een verzekering, onvoldoende dekking of een afwijzing door een verzekeraar verschuift de wettelijke verantwoordelijkheid van de professional niet naar ShineGo. Dit laat eventuele eigen wettelijke verplichtingen of aansprakelijkheid van ShineGo als platform onverlet.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">13. Belastingen en administratie</h2><p className="mt-2">De professional is zelf verantwoordelijk voor de eigen belastingaangiften, btw-verplichtingen, administratie en eventuele andere heffingen die voortvloeien uit inkomsten via ShineGo.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">14. Verboden gebruik</h2><p className="mt-2">Het is niet toegestaan het platform te gebruiken voor fraude, misleiding, discriminatie, intimidatie, onrechtmatige activiteiten, het bewust verstrekken van onjuiste informatie of het omzeilen van betalings- of veiligheidsprocedures.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">15. Accountbeperking en beëindiging</h2><p className="mt-2">ShineGo kan de toegang tot het platform tijdelijk beperken of beëindigen bij onder meer fraude, ernstige of herhaalde klachten, veiligheidsproblemen, misbruik, onjuiste verificatiegegevens, niet-nakoming van deze voorwaarden of wanneer dit wettelijk noodzakelijk is.</p><p className="mt-2">Bij een besluit om de volledige dienstverlening aan een professional te beëindigen informeert ShineGo de professional in beginsel ten minste 30 dagen vooraf op een duurzame gegevensdrager, met vermelding van de reden. Deze termijn geldt niet wanneer een wettelijke of regelgevende verplichting een snellere beëindiging vereist, wanneer sprake is van een dwingende reden volgens toepasselijk recht of wanneer herhaalde schending van de voorwaarden directe beëindiging rechtvaardigt. Bij beperking of opschorting verstrekt ShineGo, voor zover wettelijk vereist, zonder onnodige vertraging een motivering.</p><p className="mt-2">De professional kan de contractuele relatie met ShineGo beëindigen door het account te laten sluiten via de beschikbare accountmogelijkheid of door contact op te nemen via info@shinego.nl. Reeds aangenomen opdrachten, openstaande betalingen, terugbetalingen, klachten en overige administratieve verplichtingen moeten daarbij nog correct worden afgehandeld.</p><p className="mt-2">Openstaande administratieve verplichtingen, klachten, terugbetalingen en uitbetalingen kunnen ook na beëindiging nog worden afgehandeld.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">16. Aansprakelijkheid van ShineGo</h2><p className="mt-2">ShineGo faciliteert de totstandkoming en administratieve afhandeling van opdrachten en is niet verantwoordelijk voor de concrete wijze waarop de professional zijn werkzaamheden uitvoert. Iedere partij blijft verantwoordelijk voor het eigen handelen en voor verplichtingen of aansprakelijkheid die volgens de wet niet kunnen worden uitgesloten of beperkt.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">17. Wijzigingen</h2><p className="mt-2">ShineGo kan deze voorwaarden aanpassen wanneer de dienstverlening, tarieven, betaalstructuur of toepasselijke wet- en regelgeving verandert. Professionals worden in beginsel ten minste 15 dagen voordat een wijziging van toepassing wordt op een duurzame gegevensdrager geïnformeerd. Wanneer een wijziging van de professional aanzienlijke technische of commerciële aanpassingen vraagt, kan een langere termijn nodig zijn.</p><p className="mt-2">De voorafgaande termijn kan achterwege blijven wanneer ShineGo door een wettelijke of regelgevende verplichting de wijziging sneller moet doorvoeren of wanneer een onvoorziene en onmiddellijke noodzaak bestaat om fraude, malware, datalekken, cyberveiligheidsrisico's of vergelijkbare gevaren aan te pakken.</p><p className="mt-2">De professional kan de overeenkomst tijdens de aankondigingstermijn beëindigen. Wijzigingen worden niet met terugwerkende kracht toegepast, behalve wanneer dit wettelijk noodzakelijk is of wanneer de wijziging uitsluitend gunstig is voor professionals.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">18. Toepasselijk recht en geschillen</h2><p className="mt-2">Op deze voorwaarden is Nederlands recht van toepassing. Partijen proberen een geschil eerst in onderling overleg op te lossen. Voor zover dwingend recht niet anders bepaalt, wordt een geschil voorgelegd aan de bevoegde Nederlandse rechter.</p></section>

            <section><h2 className="text-xl font-bold text-slate-900">19. Contact</h2><p className="mt-2">Voor vragen over deze voorwaarden of het professional-account kan contact worden opgenomen via <a href="mailto:info@shinego.nl" className="font-semibold text-blue-600 underline hover:text-blue-700">info@shinego.nl</a>.</p></section>
          </div>
        </div>
      </div>
    </main>
  );
}
